name: qr_generatot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  path_provider: ^2.1.3
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/blank user.png
    - assets/done.png
